source "https://rubygems.org"

group :jekyll_plugins do
  gem "github-pages", "~> 206"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# security upgrade https://github.com/advisories/GHSA-mqm2-cgpr-p4m6
gem "kramdown", ">= 2.3.0"
